# Generated by Django 4.1.3 on 2022-11-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_scope_is_main_alter_scope_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag_set',
            field=models.ManyToManyField(related_name='scopes', through='articles.Scope', to='articles.tag', verbose_name='Тематики статьи'),
        ),
    ]
